### ISSUE TITLE
Roland discs all show as empty

### ISSUE THREAD

**Issue by therealfumbles** [transverberate/smpl_extract#1] opened 2024-11-18 14:53 UTC
Hi

Thanks for this tool. I've been looking for something that can handle Roland sample CDs.

Unfortunately I can't get it to list/extract any of the Roland discs I've tried. These are all plain 2048 bytes per sector iso dumps.

If I try to list the disc contents I just get `(*empty*)`. If I try to extract, the command completes with no output and nothing is extracted.

Akai discs list and extract fine so the script appears to be installed and working correctly.

Digging a little deeper I tried a couple of third-party Roland discs and one of those read and extract fine. But the other third-party disc and all the official Roland discs do not.

**Comment by transverberate** [comment] 2024-11-19 23:23
Hey,

Could you verify that the problematic Roland images are for the S-7xx series?
If they are could you reach out to me at `transverberate2@gmail.com` so I can inspect them more closely?

Thanks!

**Comment by transverberate** [comment] 2024-11-23 22:19
## Overview of Issues Found

After a discussion with @therealfumbles, I tested the following Roland S-7xx disks using this tool:
  * `Roland - Bass Coma X7`
  * `Roland - L.A. Composer, Vol. 1`
  * `Roland - SuperSax Vol. 1`
  * `ILIO - Trance Fusion`
  * `Northstar - Drumscapes`
  * `NorthStar - Global Instruments Vol. 1`

Of these, only `Trance Fusion` properly extracted (and even then, it produced the directory "`... ...........`", which is an invalid directory name on Windows 10). 

For `Bass Coma X7`, `SuperSax Vol. 1`, `Drumscapes`, and `Global Instruments Vol. 1`, the toolset indicated that each disk image was **empty**.

For `L.A. Composer, Vol. 1` the toolset **threw an error** when parsing the number of volumes (indicating that the number of volumes on the image was zero).

From these results, there appear to be three separate issues occurring for Roland S-7xx disks:
  1. failure to correctly identify valid S-7xx headers,
  2. failing to parse images containing a non-zero number of performances but zero parent volumes, and
  3. production of directories with invalid names.


## Failure to Identify Valid S-7xx Headers

Currently, this toolset expects the Roland S-7xx headers with ASCII strings at `0x20` of the form:
* ` S-760 System Disk    Ver. 2.24`
* ` S-760 System Disk    Ver. 2.19`
* ` S-760 Hard Disk      Ver. 1.26`
* etc.

This error occurs for Roland S-7xx disk images that have headers at `0x20` of the form:
* ` SYS-772 HardDisk Sys Ver. 2.19`
* ` SYS-772 HardDisk Sys Ver.2.13b`
* ` SYS-772 HardDisk Sys Ver. 2.21`
* ` SYS-772 HardDisk Sys Ver.32k-4`
* etc,

all of which are valid headers.

This issue occurs because the regex `_VERSION_REGEX` in `IdAreaAdapter` is **much too restrictive**. 

https://github.com/transverberate/smpl_extract/blob/e050c944609d420e9a26dfbc280b3ad654338c4c/smpl_extract/roland/s7xx/image.py#L98-L101

This issue can be resolved by introducing a less restrictive regex capable of passing the headers of the problematic disks. 
Some parsing that occurs during `_decode(...)` in `IdAreaAdapter` may also need to be updated.

https://github.com/transverberate/smpl_extract/blob/e050c944609d420e9a26dfbc280b3ad654338c4c/smpl_extract/roland/s7xx/image.py#L105-L142


## Failure to Parse S-7xx Images Containing Orphan Performances

The `L.A. Composer, Vol. 1` disk image contains 47 Performances yet 0 Volumes.
Because the image contains 0 Volumes, the `SafeListConstruct` for parsing `VolumeEntries` throws a `RangeException`.

https://github.com/transverberate/smpl_extract/blob/e050c944609d420e9a26dfbc280b3ad654338c4c/smpl_extract/util/constructs.py#L359-L360

This is not intended behavior for `SafeListConstruct`, as it should be able to accommodate lists with zero entries. 
This can be solved by modifying the `_parse` routine to throw a `RangeException` only when `count` is below zero.

To properly detect Performances without a parent Volume (i.e., Oprhan Performances), additional logic will need to be introduced to compare the total number of performances indicated in the `IdArea` header to the number of performances referenced in each Volume.
If there are additional performances indicated in the `IdArea` but not referenced in any Volume, a "Pseudo-Volume" containing each Orphan Performance will need to be created by the toolset and appended to the `volumes` List of the problematic `RolandS7xxImage`.

These Orphan Performances could be detected by searching the entire `Performance Directory` of the image for valid Performance Entries if the total number of Performances indicated by the `IdArea` header is less than those contained in each of the Volume Entries.


## Failure to Properly Sanitize Directory Name(s) Containing Only Spaces and Periods

Currently, exporting samples from `Trance Fusion` causes the directory "`... ...........`" to be created. This is an invalid directory name on Windows 10 (directory names must not end in a series of periods).

The `make_export_name` routine will need to be modified to prevent such names from being produced.

https://github.com/transverberate/smpl_extract/blob/e050c944609d420e9a26dfbc280b3ad654338c4c/smpl_extract/structural.py#L301-L315

A well-thought-out routine for sanitizing the names of files and directories for export is in order (directory/file names on AKAI/Roland systems allow all manner of symbols that are not valid directory/file names on Windows operating systems). 
However, delivering such a routine is beyond the scope of this issue.
In the meantime, a kludge that enables the creation of a valid Windows directory name is simply to append and prepend `0`s to names consisting entirely of spaces and periods.

**Closed as completed** 2024-11-25 01:08 UTC
